runtime: go
api_version: go1

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "cfg/Gutenbits-creds.json"

handlers:
- url: /send/*
  script: _go_app
  login: admin

- url: /books/
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
